version: 1

formatters:
  console:
    class: colorlog.ColoredFormatter
    format: '%(log_color)s %(levelname)-8s %(asctime)s.%(msecs)03d | %(message)s (%(filename)s:%(lineno)s)'
    datefmt: "%Y-%m-%d %H:%M:%S"

  file:
    format: '%(levelname)-8s %(asctime)s.%(msecs)03d | %(message)s (%(filename)s:%(lineno)s)'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: file
    filename: ${SENSOR_DATA_SENDER_LOGGER_DIR}/logs/debug.log
    when: 'W0'  # Create new log every monday
    interval: 1
#    backupCount: 5

#  file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: DEBUG
#    formatter: file
#    filename: debug.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 5

loggers:
  support_logger:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: yes

root:
  level: DEBUG
  handlers: [console, file_handler]